"""
Validator Module
===============
The Validator is a quality assurance node in the LangGraph workflow.

Responsibilities:
- Review the response generated by the specialist agent
- Check that the response meets quality standards:
  * Clear - easy to understand
  * Correct - accurate information
  * Helpful - addresses the user's needs
- Improve the response if it doesn't meet standards
- Return ONLY the final, improved response

This node runs after the routing_node selects and invokes the appropriate
specialist agent. It acts as a final review before the response is
returned to the user.

Note: The validation is done by passing the current response through a
Validator Agent that reviews and potentially rewrites it.
"""

# =============================================================================
# Imports
# =============================================================================

# Import shared components from the config module
from .config import Agent, Runner, model, config

# =============================================================================
# Validation Node Function
# =============================================================================

async def validation_node(state):
    """
    Validates and improves the agent's response.

    This is an async function that works as a LangGraph node.
    It receives the current state, creates a Validator agent,
    runs the agent on the current response, and returns the
    potentially improved response.

    Args:
        state: The current AgentState containing:
            - user_input: The original user query
            - category: The query category
            - response: The current response to validate

    Returns:
        Updated state with the (potentially) improved response

    Process:
        1. Create a fresh Validator agent with quality criteria
        2. Run the validator on the current response
        3. Replace the response with the validator's output
        4. Return the updated state
    """
    # Create a Validator agent dynamically for this validation pass
    # Using a fresh agent each time ensures clean state
    try:
        validator = Agent(
            name="Validator",

            # Use the same model as other agents for consistency
            model=model,

            # Instructions for the validator - STRICT output format
            instructions="""
            You are a Response Polish Agent. Your ONLY job is to improve customer support responses.

            RULES - FOLLOW THESE EXACTLY:
            1. You will receive a customer support response that may need minor polishing
            2. If the response is good, return it EXACTLY as-is with NO changes
            3. If the response has issues, fix ONLY the problematic parts
            4. Return the FINAL response that should be shown to the customer

            WHAT TO RETURN:
            - Return ONLY the customer-facing response text
            - Do NOT include analysis, evaluation, or commentary
            - Do NOT say "The response is:" or similar prefixes
            - Do NOT explain what you changed or why
            - Do NOT add evaluation bullet points like "Clear:", "Correct:", "Helpful:"
            - Just return the polished response itself

            EXAMPLES:

            Input: "The response is: - Clear: The language used is straightforward... "
            Output: "I understand your concern about the duplicate charge..."

            Input: "Your refund has been approved and will process in 5-7 business days."
            Output: "Your refund has been approved and will process in 5-7 business days."

            Input: "The response is: - Clear: ... - Correct: ... - Helpful: ..."
            Output: (extract and return only the actual response content)
            """,
        )

        # Run the validator on the current response
        # This passes the response text as input to the validator agent
        result = await Runner.run(
            validator,
            input=state["response"],     # The current response to validate
            run_config=config            # Standard run configuration
        )

        # Update the state with the validator's (potentially improved) response
        # result.final_output contains the validator's response
        state["response"] = result.final_output

        # Return the updated state to continue in the graph
        return state
    except Exception as e:
        print(f"Validation failed: {e}")
        return state